Khalid_ASPMVC/Controllers/CategoryController.cs
using Khalid_ASPMVC.Data;
using Khalid_ASPMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Khalid_ASPMVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        
        public IActionResult Index()
        {
            IEnumerable<Category> category = _context.Categories.ToList();
            if (category.Any())
            {
                TempData["Success"]= "Data displayed Successfully";
            }
            else
            {
                TempData["Error"]= "Data Not Found !!";
            }

            return View(category);
        }



        [HttpGet]
        public IActionResult Create() {
           
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            try
            {
                //if (category.Name == "100")
                //{
                //    ModelState.AddModelError("CustomError","Name can not be Equal 100");
                //}
                if (ModelState.IsValid)
                {
                    _context.Categories.Add(category);
                    _context.SaveChanges();
                    TempData["Create"] = "Data Created Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(category);
                }

            }
            catch (Exception ex) 
            {
                ModelState.AddModelError("", "An error occurred while adding" + ex.Message);
                return View(category);



            }
           
            
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var cate = _context.Categories.Find(Id);
            return View(cate);
        }
       
        [HttpPost]
        public IActionResult Edit(Category category)
        {
            _context.Categories.Update(category);
            _context.SaveChanges();
            TempData["Edit"] = "Data Edited Successfully";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var cate = _context.Categories.Find(Id);
            return View(cate);
        }

        [HttpPost]
        public IActionResult Delete(Category category)
        {
            _context.Categories.Remove(category);
            _context.SaveChanges();
            TempData["Delete"] = "Data Deleted Successfully";
            return RedirectToAction("Index");
        }
    }

}

Khalid_ASPMVC/Controllers/EmployeesController.cs
using Khalid_ASPMVC.Data;
using Khalid_ASPMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Khalid_ASPMVC.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }

        
        public IActionResult IndexEmployees()
        {
            IEnumerable<Employees>  employees = _context.Employees.ToList();
            if (employees.Any())
            {
                TempData["Success"] = "Data displayed Successfully";

            }
            else
            {
                TempData["Error"] = "Data Not Found !!";
            }
            return View(employees);
            

           

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost ]
        public IActionResult Create(Employees employees)
        {
            if (ModelState.IsValid)
            {

                _context.Employees.Add(employees);
                _context.SaveChanges();
                TempData["Create"] = "Data Created Successfully";
                return RedirectToAction("IndexEmployees");

            }
            else
            {
                return View(employees);
            }
                
        }

        [HttpGet]
        public IActionResult Edit(int Id)
       
        {
            var cate = _context.Employees.Find(Id);
            return View(cate);
        }
        [HttpPost]
        public IActionResult Edit(Employees employees)
        {
            _context.Employees.Update(employees);
            _context.SaveChanges();
            TempData["Edit"] = "Data Edited Successfully";
            return RedirectToAction("IndexEmployees");
        }

        [HttpGet]
        public IActionResult Delete(int Id) 
        {
            var cate =_context.Employees.Find(Id);
            return View(cate);
        }
        [HttpPost]
        public IActionResult Delete(Employees employees)
        {
            _context.Employees.Remove(employees);
            _context.SaveChanges();
            TempData["Delete"] = "Data Deleted Successfully";
            return RedirectToAction("IndexEmployees");
        }
    }
}

Khalid_ASPMVC/Controllers/ProductController.cs
using Khalid_ASPMVC.Data;
using Khalid_ASPMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Khalid_ASPMVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ProductController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult IndexProduct()

        {
            IEnumerable<Product> products = _context.Products.ToList();
            if (products.Any())
            {
                TempData["Success"] = "Data displayed Successfully";
            }
            else
            {
                TempData["Error"] = "Data Not Found !!";
            }

            return View(products);



        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Product product)
        {
          
            

                if (ModelState.IsValid)
                {
                    _context.Products.Add(product);
                    _context.SaveChanges();
                    TempData["Create"] = "Data Created Successfully";
                    return RedirectToAction("IndexProduct");

                }
                else
                {
                    return View(product);
                }
            }
           

            



            [HttpGet]
            public IActionResult Edit(int Id)
            {
                var cate = _context.Products.Find(Id);
                return View(cate);
            }

            [HttpPost]
            public IActionResult Edit(Product product)
            {
                _context.Products.Update(product);
                _context.SaveChanges();
                TempData["Edit"] = "Data Edited Successfully";
                return RedirectToAction("IndexProduct");

            }

            [HttpGet]
            public IActionResult Delete(int Id)
            {
                var cate = _context.Products.Find(Id);
                return View(cate);
            }
            [HttpPost]
            public IActionResult Delete(Product product)
            {
                _context.Products.Remove(product);
                _context.SaveChanges();
                TempData["Delete"] = "Data Deleted Successfully";
                return RedirectToAction("IndexProduct");

            }
        }
    }

Khalid_ASPMVC/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Khalid_ASPMVC</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/Dashboard/css/styles.css" rel="stylesheet" />
    <script src="~/Dashboard/js/scripts.js" crossorigin="anonymous"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />


</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3 m-2" href="index.html">
            <img src="~/Dashboard/K.img.png" alt="Khaliid Logo" height="80" >
        </a>

        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Layouts
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Category" asp-action="Index">Categories</a>
                                <a class="nav-link" asp-controller="Product" asp-action="IndexProduct">Products</a>
                                <a class="nav-link" asp-controller="Employees" asp-action="IndexEmployees">Employees</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">401 Page</a>
                                        <a class="nav-link" href="404.html">404 Page</a>
                                        <a class="nav-link" href="500.html">500 Page</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
            @RenderBody()

            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Dashboard/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/Dashboard/assets/demo/chart-area-demo.js"></script>
    <script src="~/Dashboard/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/Dashboard/js/datatables-simple-demo.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Khalid_ASPMVC/Views/Shared/_NotificationsPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>


@if (TempData["Success"] != null)
{

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"] ✅
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    <script>
        toastr.success('@TempData["Success"]','Success');
    </script>

}
@if (TempData["Error"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["Error"] ❌
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    <script>
        toastr.Error('@TempData["Error"]','Error');
    </script>
    
}
@if (TempData["Create"] != null)
{

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Create"] ✅
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    <script>
        toastr.Create('@TempData["Create"]','Create');
    </script>

    @* <script>
        toastr.success('Have fun storming the castle!', 'Miracle Max Says')
    </script> *@
}
@if (TempData["Edit"] != null)
{

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Edit"] ✅
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    <script>
        toastr.Edit('@TempData["Edit"]','Edit');
    </script>
}
@if (TempData["Delete"] != null)
{

    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["Delete"] ✅
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    <script>
        toastr.Delete('@TempData["Delete"]','Delete');
    </script>
}